import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Globals from "@/modules/Globals";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href={`${Globals.BASE_URL}assets/css/main.min.css`}
          rel="stylesheet"
          
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
